# Generated by Django 5.0 on 2024-07-05 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
